dist: trusty
language: node_js
node_js:
  - '6'
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS restypie_test;" -u root
script:
  - npm test
git:
  depth: 5
